import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import Landing from './pages/Landing';
import AdminDashboard from './pages/AdminDashboard';
import AdminTicketDetail from './pages/AdminTicketDetail';
import AdminImports from './pages/AdminImports';
import AdminPeople from './pages/AdminPeople';
import AdminReports from './pages/AdminReports';
import AdminRemote from './pages/AdminRemote';
import AdminNotifications from './pages/AdminNotifications';
import EngineerDashboard from './pages/EngineerDashboard';
import EngineerTicketDetail from './pages/EngineerTicketDetail';
import EngineerTeam from './pages/EngineerTeam';
import EngineerRemote from './pages/EngineerRemote';
import EngineerApprovals from './pages/EngineerApprovals';
import UserHome from './pages/UserHome';
import UserNewTicket from './pages/UserNewTicket';
import UserTicketDetail from './pages/UserTicketDetail';
import UserNotifications from './pages/UserNotifications';
const App = () => (_jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Landing, {}) }), _jsx(Route, { path: "/admin", element: _jsx(AdminDashboard, {}) }), _jsx(Route, { path: "/admin/tickets/:ticketId", element: _jsx(AdminTicketDetail, {}) }), _jsx(Route, { path: "/admin/imports", element: _jsx(AdminImports, {}) }), _jsx(Route, { path: "/admin/people", element: _jsx(AdminPeople, {}) }), _jsx(Route, { path: "/admin/reports", element: _jsx(AdminReports, {}) }), _jsx(Route, { path: "/admin/remote", element: _jsx(AdminRemote, {}) }), _jsx(Route, { path: "/admin/notifications", element: _jsx(AdminNotifications, {}) }), _jsx(Route, { path: "/engineer", element: _jsx(EngineerDashboard, {}) }), _jsx(Route, { path: "/engineer/tickets/:ticketId", element: _jsx(EngineerTicketDetail, {}) }), _jsx(Route, { path: "/engineer/team", element: _jsx(EngineerTeam, {}) }), _jsx(Route, { path: "/engineer/remote", element: _jsx(EngineerRemote, {}) }), _jsx(Route, { path: "/engineer/approvals", element: _jsx(EngineerApprovals, {}) }), _jsx(Route, { path: "/user", element: _jsx(UserHome, {}) }), _jsx(Route, { path: "/user/tickets/new", element: _jsx(UserNewTicket, {}) }), _jsx(Route, { path: "/user/tickets/:ticketId", element: _jsx(UserTicketDetail, {}) }), _jsx(Route, { path: "/user/notifications", element: _jsx(UserNotifications, {}) })] }) }));
export default App;
